-- Apply ONCE. Creates only the public editorial catalog; does not touch profiles.
begin;
create table public.admit_programs (
  id text primary key check (id ~ '^[a-z0-9-]{1,100}$'),
  data jsonb not null,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint admit_programs_object check (jsonb_typeof(data) = 'object'),
  constraint admit_programs_id check (data->>'id' = id),
  constraint admit_programs_size check (octet_length(data::text) <= 16384)
);
alter table public.admit_programs enable row level security;
alter table public.admit_programs force row level security;
revoke all on public.admit_programs from public, anon, authenticated;
grant select on public.admit_programs to anon, authenticated;
create policy admit_programs_read_active on public.admit_programs
  for select to anon, authenticated using (active = true);
comment on table public.admit_programs is 'Public sourced program catalog. Only administrators may edit. No applicant information.';
insert into public.admit_programs (id, data) values
('aitu-software', '{"id":"aitu-software","uni":"aitu","university":"Astana IT University","mark":"AITU","country":"KZ","city":["Астана","Астана","Astana"],"color":"violet","years":3,"tuition":2500000,"currency":"KZT","feeYear":"2026/27","source":"https://astanait.edu.kz/en/bachelor","admissions":"https://astanait.edu.kz/en/bachelor","funding":"grant","language":"en","title":["Разработка программного обеспечения","Бағдарламалық инженерия","Software Engineering"],"fields":["technology"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('aitu-cs', '{"id":"aitu-cs","uni":"aitu","university":"Astana IT University","mark":"AITU","country":"KZ","city":["Астана","Астана","Astana"],"color":"violet","years":3,"tuition":2500000,"currency":"KZT","feeYear":"2026/27","source":"https://astanait.edu.kz/en/bachelor","admissions":"https://astanait.edu.kz/en/bachelor","funding":"grant","language":"en","title":["Компьютерные науки","Компьютерлік ғылымдар","Computer Science"],"fields":["technology"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('aitu-data', '{"id":"aitu-data","uni":"aitu","university":"Astana IT University","mark":"AITU","country":"KZ","city":["Астана","Астана","Astana"],"color":"violet","years":3,"tuition":2500000,"currency":"KZT","feeYear":"2026/27","source":"https://astanait.edu.kz/en/bachelor","admissions":"https://astanait.edu.kz/en/bachelor","funding":"grant","language":"en","title":["Анализ больших данных","Үлкен деректерді талдау","Big Data Analysis"],"fields":["technology","science"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('aitu-electronics', '{"id":"aitu-electronics","uni":"aitu","university":"Astana IT University","mark":"AITU","country":"KZ","city":["Астана","Астана","Astana"],"color":"violet","years":3,"tuition":2500000,"currency":"KZT","feeYear":"2026/27","source":"https://astanait.edu.kz/en/bachelor","admissions":"https://astanait.edu.kz/en/bachelor","funding":"grant","language":"en","title":["Электронная инженерия","Электрондық инженерия","Electronic Engineering"],"fields":["engineering"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('aitu-iot', '{"id":"aitu-iot","uni":"aitu","university":"Astana IT University","mark":"AITU","country":"KZ","city":["Астана","Астана","Astana"],"color":"violet","years":3,"tuition":2500000,"currency":"KZT","feeYear":"2026/27","source":"https://astanait.edu.kz/en/bachelor","admissions":"https://astanait.edu.kz/en/bachelor","funding":"grant","language":"en","title":["Промышленный интернет вещей","Заттардың өнеркәсіптік интернеті","Industrial Internet of Things"],"fields":["engineering","technology"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('aitu-management', '{"id":"aitu-management","uni":"aitu","university":"Astana IT University","mark":"AITU","country":"KZ","city":["Астана","Астана","Astana"],"color":"violet","years":3,"tuition":2500000,"currency":"KZT","feeYear":"2026/27","source":"https://astanait.edu.kz/en/bachelor","admissions":"https://astanait.edu.kz/en/bachelor","funding":"grant","language":"en","title":["IT-менеджмент","IT-менеджмент","IT Management"],"fields":["business","technology"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('aitu-media', '{"id":"aitu-media","uni":"aitu","university":"Astana IT University","mark":"AITU","country":"KZ","city":["Астана","Астана","Astana"],"color":"violet","years":3,"tuition":2500000,"currency":"KZT","feeYear":"2026/27","source":"https://astanait.edu.kz/en/bachelor","admissions":"https://astanait.edu.kz/en/bachelor","funding":"grant","language":"en","title":["Медиатехнологии","Медиатехнологиялар","Media Technologies"],"fields":["creative","technology"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('aitu-journalism', '{"id":"aitu-journalism","uni":"aitu","university":"Astana IT University","mark":"AITU","country":"KZ","city":["Астана","Астана","Astana"],"color":"violet","years":3,"tuition":2500000,"currency":"KZT","feeYear":"2026/27","source":"https://astanait.edu.kz/en/bachelor","admissions":"https://astanait.edu.kz/en/bachelor","funding":"grant","language":"en","title":["Цифровая журналистика","Цифрлық журналистика","Digital Journalism"],"fields":["creative","humanities","social"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('nu-cs', '{"id":"nu-cs","uni":"nu","university":"Nazarbayev University","mark":"NU","country":"KZ","city":["Астана","Астана","Astana"],"color":"gold","years":4,"tuition":null,"currency":"USD","feeYear":null,"source":"https://nu.edu.kz/sprogram/bachelor-of-science-in-computer-science/","admissions":"https://nu.edu.kz/admissions/how-to-apply/foundation-undergraduate/regular-admissions/","funding":"grant","language":"en","title":["Компьютерные науки","Компьютерлік ғылымдар","Computer Science"],"fields":["technology"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('nu-biology', '{"id":"nu-biology","uni":"nu","university":"Nazarbayev University","mark":"NU","country":"KZ","city":["Астана","Астана","Astana"],"color":"gold","years":4,"tuition":null,"currency":"USD","feeYear":null,"source":"https://nu.edu.kz/sprogram/bachelor-of-science-in-biological-sciences/","admissions":"https://nu.edu.kz/admissions/how-to-apply/foundation-undergraduate/regular-admissions/","funding":"grant","language":"en","title":["Биологические науки","Биология ғылымдары","Biological Sciences"],"fields":["science","medicine"],"checkedAt":"2026-09-18","deadline":null,"note":"biology","entry":null,"englishLevel":null}'::jsonb),
('nu-politics', '{"id":"nu-politics","uni":"nu","university":"Nazarbayev University","mark":"NU","country":"KZ","city":["Астана","Астана","Astana"],"color":"gold","years":4,"tuition":null,"currency":"USD","feeYear":null,"source":"https://ssh.nu.edu.kz/bapsir","admissions":"https://nu.edu.kz/admissions/how-to-apply/foundation-undergraduate/regular-admissions/","funding":"grant","language":"en","title":["Политология и международные отношения","Саясаттану және халықаралық қатынастар","Political Science & International Relations"],"fields":["social"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('nu-sociology', '{"id":"nu-sociology","uni":"nu","university":"Nazarbayev University","mark":"NU","country":"KZ","city":["Астана","Астана","Astana"],"color":"gold","years":4,"tuition":null,"currency":"USD","feeYear":null,"source":"https://ssh.nu.edu.kz/ugprograms","admissions":"https://nu.edu.kz/admissions/how-to-apply/foundation-undergraduate/regular-admissions/","funding":"grant","language":"en","title":["Социология","Әлеуметтану","Sociology"],"fields":["social"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('nu-linguistics', '{"id":"nu-linguistics","uni":"nu","university":"Nazarbayev University","mark":"NU","country":"KZ","city":["Астана","Астана","Astana"],"color":"gold","years":4,"tuition":null,"currency":"USD","feeYear":null,"source":"https://ssh.nu.edu.kz/ugprograms","admissions":"https://nu.edu.kz/admissions/how-to-apply/foundation-undergraduate/regular-admissions/","funding":"grant","language":"en","title":["Лингвистика и мировая литература","Лингвистика және әлем әдебиеті","Linguistics & World Literature"],"fields":["humanities"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('nu-chemistry', '{"id":"nu-chemistry","uni":"nu","university":"Nazarbayev University","mark":"NU","country":"KZ","city":["Астана","Астана","Astana"],"color":"gold","years":4,"tuition":null,"currency":"USD","feeYear":null,"source":"https://ssh.nu.edu.kz/ugprograms","admissions":"https://nu.edu.kz/admissions/how-to-apply/foundation-undergraduate/regular-admissions/","funding":"grant","language":"en","title":["Химия","Химия","Chemistry"],"fields":["science"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('ud-cs', '{"id":"ud-cs","uni":"debrecen","university":"University of Debrecen","mark":"UD","country":"HU","city":["Дебрецен","Дебрецен","Debrecen"],"color":"green","years":3,"tuition":7000,"currency":"USD","feeYear":"2026/27","source":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","admissions":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","funding":"check","language":"en","title":["Компьютерные науки","Компьютерлік ғылымдар","Computer Science"],"fields":["technology"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('ud-business', '{"id":"ud-business","uni":"debrecen","university":"University of Debrecen","mark":"UD","country":"HU","city":["Дебрецен","Дебрецен","Debrecen"],"color":"green","years":3.5,"tuition":7000,"currency":"USD","feeYear":"2026/27","source":"https://edu.unideb.hu/p/business-administration-and-management-bsc","admissions":"https://edu.unideb.hu/p/business-administration-and-management-bsc","funding":"check","language":"en","title":["Управление бизнесом","Бизнесті басқару","Business Administration & Management"],"fields":["business"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":"math","englishLevel":"B2"}'::jsonb),
('ud-nursing', '{"id":"ud-nursing","uni":"debrecen","university":"University of Debrecen","mark":"UD","country":"HU","city":["Дебрецен","Дебрецен","Debrecen"],"color":"green","years":4,"tuition":7500,"currency":"USD","feeYear":"2026/27","source":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","admissions":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","funding":"check","language":"en","title":["Сестринское дело","Мейіргер ісі","Nursing"],"fields":["medicine"],"checkedAt":"2026-09-18","deadline":null,"note":"nursing","entry":"biology","englishLevel":null}'::jsonb),
('ud-biology', '{"id":"ud-biology","uni":"debrecen","university":"University of Debrecen","mark":"UD","country":"HU","city":["Дебрецен","Дебрецен","Debrecen"],"color":"green","years":3,"tuition":6500,"currency":"USD","feeYear":"2026/27","source":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","admissions":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","funding":"check","language":"en","title":["Биология","Биология","Biology"],"fields":["science","medicine"],"checkedAt":"2026-09-18","deadline":null,"note":"biology","entry":null,"englishLevel":null}'::jsonb),
('ud-english', '{"id":"ud-english","uni":"debrecen","university":"University of Debrecen","mark":"UD","country":"HU","city":["Дебрецен","Дебрецен","Debrecen"],"color":"green","years":null,"tuition":null,"currency":"USD","feeYear":"2026/27","source":"https://edu.unideb.hu/p/faculty-of-humanities","admissions":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","funding":"check","language":"en","title":["Английский язык и американистика","Ағылшын тілі және америкатану","English & American Studies"],"fields":["humanities"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('ud-media', '{"id":"ud-media","uni":"debrecen","university":"University of Debrecen","mark":"UD","country":"HU","city":["Дебрецен","Дебрецен","Debrecen"],"color":"green","years":null,"tuition":null,"currency":"USD","feeYear":null,"source":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","admissions":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","funding":"check","language":"en","title":["Коммуникация и медиаисследования","Коммуникация және медиа зерттеулері","Communication and Media Studies"],"fields":["creative","social"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('ud-civil', '{"id":"ud-civil","uni":"debrecen","university":"University of Debrecen","mark":"UD","country":"HU","city":["Дебрецен","Дебрецен","Debrecen"],"color":"green","years":4,"tuition":7500,"currency":"USD","feeYear":"2026/27","source":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","admissions":"https://edu.unideb.hu/p/tuition-fee-application-entrance-fee","funding":"check","language":"en","title":["Гражданское строительство","Азаматтық құрылыс","Civil Engineering"],"fields":["engineering"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb),
('ub-economics', '{"id":"ub-economics","uni":"bologna","university":"University of Bologna","mark":"UB","country":"IT","city":["Болонья","Болонья","Bologna"],"color":"rose","years":3,"tuition":null,"currency":"EUR","feeYear":null,"source":"https://www.unibo.it/en/study/first-and-single-cycle-degree/programme/2026/6646","admissions":"https://corsi.unibo.it/1cycle/EconomicsAndFinance","funding":"check","language":"en","title":["Экономика и финансы","Экономика және қаржы","Economics & Finance"],"fields":["business"],"checkedAt":"2026-09-18","deadline":null,"note":null,"entry":null,"englishLevel":null}'::jsonb);
commit;
select count(*) as program_count from public.admit_programs;
